version: '3.3'

services:

  us-east1:
    image: ${CRDB_VERSION}
    container_name: us-east1
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start --insecure --store=us-east1 --listen-addr=us-east1:26257 --http-addr=us-east1:8080 --join=us-east1:26257,us-east2:26258,us-east3:26259,us-east4:26260 --locality=region=us-east,zone=us-east1
    volumes:
      - "${PWD}/cockroach-data/us-east1:/cockroach/cockroach-data"
      - "${PWD}/scripts:/scripts"
    restart: always

  us-east2:
    image: ${CRDB_VERSION}
    container_name: us-east2
    ports:
      - "26258:26258"
      - "8081:8081"
    command: start --insecure --store=us-east2 --listen-addr=us-east2:26258 --http-addr=us-east2:8081 --join=us-east1:26257,us-east2:26258,us-east3:26259,us-east4:26260 --locality=region=us-east,zone=us-east2
    volumes:
      - "${PWD}/cockroach-data/us-east2:/cockroach/cockroach-data"
      - "${PWD}/scripts:/scripts"
    restart: always

  us-east3:
    image: ${CRDB_VERSION}
    container_name: us-east3
    ports:
      - "26259:26257"
      - "8083:8080"
    command: start --insecure --store=us-east3 --listen-addr=us-east3:26259 --http-addr=us-east3:8082 --join=us-east1:26257,us-east2:26258,us-east3:26259,us-east4:26260 --locality=region=us-east,zone=us-east3
    volumes:
      - "${PWD}/cockroach-data/us-east3:/cockroach/cockroach-data"
      - "${PWD}/scripts:/scripts"
    restart: always

  us-east4:
    image: ${CRDB_VERSION}
    container_name: us-east4
    ports:
      - "26260:26257"
      - "8084:8080"
    command: start --insecure --store=us-east4 --listen-addr=us-east4:26260 --http-addr=us-east4:8083 --join=us-east1:26257,us-east2:26258,us-east3:26259,us-east4:26260 --locality=region=us-east,zone=us-east4
    volumes:
      - "${PWD}/cockroach-data/us-east4:/cockroach/cockroach-data"
      - "${PWD}/scripts:/scripts"
    restart: always
